config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  mount RedactorRails::Engine => '/redactor_rails'
  get '/users/sendmailer', to: 'users#sendmailer', as: 'sendmailer'
  get '/users/subscribe', to: 'users#subscribe', as: 'subscribe'
  get '/users/testmail', to: 'users#testmail', as: 'testmail'
  post '/users/sendtest', to: 'users#sendtest', as: 'sendtest'

  get '/auth/:provider/callback', to: 'spreadsheets#new',    as: 'google_spreadsheet'
  get '/auth/failure',            to: 'spreadsheets#failure'

  resources :users, :newsletters, :home, :user_mailer, :spreadsheets

  root :to => 'newsletters#index'

end

app/models/newsletter.rb
class Newsletter
  include Mongoid::Document
    field :content,     type: String 
    field :sent_on,     type: Date
    field :users_count,  type: Integer, default: 0

    validates :content, presence: true

    has_many :users

end

app/models/redactor_rails/asset.rb
class RedactorRails::Asset
  include Mongoid::Document
  include Mongoid::Timestamps

  include RedactorRails::Orm::Mongoid::AssetBase

  delegate :url, :current_path, :size, :content_type, :filename, :to => :data
  validates_presence_of :data
end

app/models/redactor_rails/document.rb
class RedactorRails::Document < RedactorRails::Asset
  mount_uploader :data, RedactorRailsDocumentUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end

  def thumb
    # Could theoretically provide an icon set here
    # to match against the extensions
    # but for now it's nil to address the bug
    nil
  end
end

app/models/redactor_rails/picture.rb
class RedactorRails::Picture < RedactorRails::Asset
  mount_uploader :data, RedactorRailsPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/spreadsheet.rb
class Spreadsheet
  include Mongoid::Document

  field :spreadsheet_id,    type: String
  field :spreadsheet_title, type: String
  field :refresh_token,     type: String
  field :expires_at,        type: Time
  field :access_token,      type: String

  validates :access_token,   presence:   true, uniqueness: true

  def add_tokens(tokens = {})
    self['access_token']   = tokens.fetch('token')
    self['refresh_token']  = tokens.fetch('refresh_token')
    self['expires_at']     = tokens.fetch('expires_at')
  end

  def add_spreadsheet_credentials(credentials = {})
    if Spreadsheet.where('spreadsheet_id' => credentials['id']).to_a[0]
      return false
    else
      self['spreadsheet_id']    = credentials['id']
      self['spreadsheet_title'] = credentials['title']
    end

    true
  end

  def access_token
    self['access_token']
  end

end

app/models/user.rb
class User
  include Mongoid::Document

  field :email_id,      type: String
  field :username,      type: String
  field :is_subscribed, type: Boolean
  field :joined_on,     type: Date
  field :source,        type: String
  field :sent_on,       type: Array

  validates :email_id, presence: true
  validates_format_of :email_id, with: /\A[a-z0-9]+([\w.+-]*[a-z0-9])*@([a-z]+[\w-]*\.)+[a-z]+\Z/i, on: :create
  validates :username, presence: true
  validates :email_id, uniqueness: true

  belongs_to :newsletter, counter_cache: :users_count

  def self.add_users_from_worksheet(worksheet, column = 1)
    fails = []

    worksheet.rows.count.times do |i|
      user = User.new(
          email_id:       worksheet[i + 1, column],
          username:       worksheet[i + 1, column - 1],
          is_subscribed:  true,
          joined_on:      Date.today,
          source:         'Google Spreadsheet')

      if user.save
      else
        fails << worksheet[i + 1, column]
      end
    end
    fails.delete_at(0)
    fails
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController

  def index
    @newsletters = Newsletter.order_by([:sent_on, :desc])
  end

  def show
    @newsletter = Newsletter.find(params[:id])
  end

  def new 
    @newsletter = Newsletter.new
  end



  def create 
    @newsletter = Newsletter.new(newsletters_params)
    if @newsletter.save
      @newsletter.update(sent_on: Date.today)
      redirect_to newsletters_path
    else
      render action: 'new'
    end
  end

  def edit
    @newsletter = Newsletter.find(params[:id])
  end

  def update
    @newsletter = Newsletter.find(params[:id])
    if @newsletter.update_attributes(newsletters_params)
      redirect_to newsletters_path
    else
      render action: 'edit'
    end
  end

  def destroy
    @newsletter = Newsletter.find(params[:id])
    @newsletter.destroy
    redirect_to newsletters_path
  end

  private
  def newsletters_params
    params.require(:newsletter).permit(:id, :content, :sent_on, :users_count)
  end
end

app/controllers/spreadsheets_controller.rb
class SpreadsheetsController < ApplicationController
  require 'google'
  include Google::Spreadsheets

  def index
    @spreadsheets = Spreadsheet.all.to_a
  end

  def new
    if params[:access_token]
      spreadsheet = Spreadsheet.where(access_token: params['access_token'])[0]
    else
      spreadsheet = Spreadsheet.new
      spreadsheet.add_tokens(request.env['omniauth.auth'].fetch('credentials'))
    end

    if spreadsheet.save
      # Spreadsheets from google
      @spreadsheets = list(spreadsheet)
      @token        = spreadsheet.access_token
    else
      # Handle if data does not get saved
      @msg = 'Getting same access token. Try deleting '
    end
  end

  def edit
    token = spreadsheet_params['token']
    spreadsheet = Spreadsheet.where(access_token: token)[0]

    if spreadsheet && spreadsheet.add_spreadsheet_credentials(spreadsheet_params)
      spreadsheet.save
    else
      @error = 'Already Present'
    end

    @spreadsheets = Spreadsheet.all.to_a

    render action: 'index'
  end

  def update
    spreadsheet = Spreadsheet.find(params['id'])
    @worksheet  = worksheets(spreadsheet)
    @fails = User.add_users_from_worksheet(@worksheet, 2)
  end

  def destroy
    Spreadsheet.find(params['id']).delete
    redirect_to spreadsheets_path
  end

  def failure
    if params['message'].match('access_denied')
      @msg = 'Account integration Failed. User Refused to grant permissions'
    end
    @spreadsheets = Spreadsheet.all.to_a
    render action: 'index'
  end

  #################################
  private
  #################################

    def spreadsheet_params
      params.permit(:id, :title, :token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    if params[:user]

    else
      @user = User.new
    end
  end

  def create
    @user = User.new(users_params)
    @user.sent_on = Array.new
    if @user.save
      @user.update(is_subscribed: true, joined_on: Date.today, source: "Manual",sent_on: Array.new)
      redirect_to users_path
    else
      render action: 'new'
    end
  end

  def testmail
  end

  def sendtest
    emails = params[:email][:email_id].split(",")
    Enqueue.perform_async(emails)

    redirect_to newsletters_path
  end
  
  def subscribe
    @user = User.find(params[:id])
    @user.update(is_subscribed: 'false')
  end
  
  def sendmailer

    #@users = User.where(is_subscribed: "true")
    HardWorker.perform_async(true)

    redirect_to newsletters_path
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(users_params)
      redirect_to users_path
    else
      render action: 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end
  
  private
  def users_params
    params.require(:user).permit(:id, :email_id, :is_subscribed, :joined_on, :source, :username)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/helpers/spreadsheets_helper.rb
module SpreadsheetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
  %title Lightair
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
  %body
    %div.nav.navbar-default.navbar-fixed-top{role: "navigation"}
      %div.container
        %div.nav-collapse
          %ul.nav.navbar-nav
            %li.active
              %a{href: "#{newsletters_path}"}
                %strong LightAir
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown"}
                %strong
                  Newsletters
                  %span.caret
              %ul.dropdown-menu{role: "menu", "aria-labelledby" => "dropdownMenu" }
                %li
                  %a{role: "menuitem", tabindex: "1", href: "#{newsletters_path}"}  Show Newsletters
                %li
                  %a{role: "menuitem", tabindex: "2", href: "#{new_newsletter_path}"} Add Newsletter
            %li
              %a{href: "#{users_path}"}
                %strong Show Users
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown"}
                %strong
                  Add Users
                  %span.caret
              %ul.dropdown-menu{role: "menu", "aria-labelledby" => "dropdownMenu" }
                %li
                  %a{role: "menuitem", tabindex: "-1", href: "#{new_user_path}"}Add Manually
                %li
                  %a{role: "menuitem", tabindex: "-2", href: "#{spreadsheets_path}"}Google Spreadsheets

        %ul.nav.navbar-nav.navbar-right
          %li
            %a
              %strong
                Subscriber count :
                =User.count
      %div.col-md-10
      %div.col-md-2
        %a{href:"https://github.com/you"}
          %img{style:"position: absolute; top: 0; right: 0; border: 0;",
            src:"https://camo.githubusercontent.com/365986a132ccd6a44c23a9169022c0b5c890c387/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f7265645f6161303030302e706e67",
            alt:"Fork me on GitHub",
            'data-canonical-src'=>"https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png"}
    
    %div.container#content
      %div.col-md-1
      %div.col-md-9
        %div.row
          %div= yield

    %div.footer
      %div.container
        %center
          %strong JoshSoftware's
          %br RubyOnRails Experts

app/views/newsletters/_form.html.haml
.container
  = simple_form_for (@newsletter) do |news|
    .inputs
      = news.text_area :content, :placeholder => "Input here..", :class => "redactor", :rows => 20, :cols => 40
      = news.button :submit, class: "btn btn-primary"

app/views/newsletters/edit.html.haml
= render :partial => "form"

app/views/newsletters/index.html.haml
%div.pull-right{'z-index' => 3452345}
  = link_to "Send Mail", sendmailer_path, class: "btn btn-danger", :data => { :confirm => 'Are you sure?'}
  = link_to "Test Mail", testmail_path, class: "btn btn-success"
%h4
  %strong Newsletters
%table.table
  -count=3
  -@newsletters.each do |newsletter|
    -if count > 2
      -count=0
      %tr
    %td
      %center
        %a.link{href: "#{newsletter_path(newsletter)}" }
          %div.tile.thumbnail
            %img{src: "images/newsletter.jpg"}
            %div.cap
              %h4
                %center
                  =newsletter.sent_on.strftime("%B %Y")
    -count+=1

app/views/newsletters/new.html.haml
= render :partial => "form"

app/views/newsletters/show.html.haml
= raw @newsletter.content
=@newsletter.users_count

app/views/spreadsheets/edit.html.haml
=debug @sp

app/views/spreadsheets/index.html.haml
= @msg if @msg
%h4
  =link_to 'Add New Spreadsheet', '/auth/google/', class: "btn btn-primary"

%table.table.table-striped
  %tr.info
    %td
      %strong #
    %td
      %strong
        Spreadsheets (
        =Spreadsheet.count
        )
    %td
      %strong Operations
  - i = 0
  - @spreadsheets.each do |ss|
    %tr
      %td
        = i = i + 1
      %td
        -if ss['spreadsheet_title']
          =ss['spreadsheet_title']
        -else
          =link_to 'Get Spreadsheet', new_spreadsheet_path(access_token: ss['access_token'])
          -if @error
            (
            =@error
            )
      %td
        =link_to 'Delete', spreadsheet_path(ss), method: :delete, class: "btn btn-mini btn-danger"
        -if ss['spreadsheet_title']
          |
          =link_to 'Add Users', spreadsheet_path(ss), method: :patch

app/views/spreadsheets/new.html.haml
-if @msg
  =@msg
-else
  -count = @spreadsheets.count
  -count.times do |i|
    =link_to @spreadsheets[i]['title'], edit_spreadsheet_path(@spreadsheets[i]['id'], title: @spreadsheets[i]['title'], token: @token) if @spreadsheets[i]['mimeType'].include?('spreadsheet')
    %br

app/views/spreadsheets/update.html.haml
%table.table.table-striped
  %tr
    %td{colspan: 3}
      %center
        %strong REPORT
        %br
      Following Email Ids were not added to database as they didn't satisfy our validations criteria.
      %table.table.table-striped
        %tr
          %td It should start with
          %td An alphabet or a number
        %tr
          %td It can contain
          %td '_'
        %tr
          %td These Characters are not allowed
          %td '.' '+' '-'
        %tr
          %td It should end with
          %td An alphabet or a number

  %tr
    %td
      %strong #
    %td
      %strong User Email Id
  - index = 0
  - @fails.each do |user|
    %tr
      %td
        =index
        -index = index + 1
      %td
        = user
    %tr

app/views/users/_form.html.haml
.panel.panel-primary
  .panel-heading
    New User
  .panel-body
    = simple_form_for (@user), html: {role: 'form', class: 'form-horizontal'} do |f|
      = f.input :email_id, input_html:{class: 'span2'}
      = f.input :username
      = f.input :is_subscribed, :as => :select
      = f.input :joined_on, input_html: { 'data-behaviour' => 'datepicker'}
      = f.input :source
      = f.button :submit, class: "btn btn-success"

:javascript
  $('[data-behaviour~=datepicker]').datepicker({
    format: 'yyyy-mm-dd'
  })
  

app/views/users/edit.html.haml
= simple_form_for (@user), html: {role: 'form', class: 'form-horizontal'} do |f|
  %table
    %tr
      %td
        = f.input :email_id, input_html:{class: 'span2'}
        = f.input :username
        = f.input :is_subscribed, :as => :select
        = f.input :joined_on, input_html: { 'data-behaviour' => 'datepicker'}
        = f.input :source
        = f.button :submit, class: "btn btn-success"

:javascript
  $('[data-behaviour~=datepicker]').datepicker({
    format: 'yyyy-mm-dd'
  })
  

app/views/users/index.html.haml
%table.table.table-striped 
  %tr
    %td
      %strong 
        = "#"
    %td
      %strong
        User's Email Id 
    %td
      %strong
        Username
    %td{colspan: 2}
      %center
        %strong
          Edit
  -count = 0
  - @users.each do |user|
    -if user.is_subscribed == true
      -str = :success
    -else
      -str = :warning
    -count = count + 1
    %tr{:class => str}
      %td
        =count
      %td
        = link_to user.email_id, user_path(user)
      %td
        = user.username
      %td
        = link_to "Edit", edit_user_path(user), class: "btn btn-mini btn-success"
      %td
        = link_to "Delete", user_path(user), method: :delete, class: "btn btn-mini btn-danger"

app/views/users/new.html.haml
= simple_form_for (@user), html: {role: 'form', class: 'form-horizontal'} do |f|
  %table
    %tr
      %td
        = f.input :email_id, input_html:{class: 'span2'}
        = f.input :username
        = f.button :submit, class: "btn btn-success"
  

app/views/users/show.html.haml
=@user.username
=@user.source
=@user.joined_on
=@user.is_subscribed

app/views/users/subscribe.html.haml
%h2 
  %center
  Unsubscribed successfully

app/views/users/testmail.html.haml
.panel.panel-primary
  .panel-heading 
    Test Mail
  .panel-body
    = form_for :email, as: :post, url: sendtest_path do |f|
      = f.text_area :email_id
      = f.button :submit, class: "btn btn-success"